apiVersion: apps/v1
kind: Deployment
metadata:
  name: photostudio-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photostudio-app
  template:
    metadata:
      labels:
        app: photostudio-app
    spec:
      containers:
      - name: photostudio-app
        image: elzabeth03/recruitment-app-project-recruitment-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        env:
        - name: MONGODB_AUTH_URI
          valueFrom:
            configMapKeyRef:
              name: photostudio-config
              key: MONGODB_AUTH_URI

        - name: MONGODB_FEEDBACK_URI
          valueFrom:
            configMapKeyRef:
              name: photostudio-config
              key: MONGODB_FEEDBACK_URI

        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: photostudio-config
              key: MONGODB_URI

        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: photostudio-config
              key: PORT
---
apiVersion: v1
kind: Service
metadata:
  name: photostudio-service
spec:
  selector:
    app: photostudio-app
  ports:
  - port: 4000
    targetPort: 4000
    nodePort: 30020
  type: NodePort
