version: "3.8"

services:

  photostudio-app:
    build: .
    container_name: photostudio-app

    ports:
      - "3000:3000"   # host:container

    depends_on:
      - mongo
    env_file:
      - .env
    
    restart: always

  mongo:
    image: mongo:7
    container_name: photostudio-db

    ports:
      - "27018:27017"   

    volumes:
      - mongo-data:/data/db

    restart: always

volumes:
  mongo-data:
